### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by dvdsk** [smasher164/pw-volume#13]
I like to cargo install all of my rust tools (such as exa, bat, difftastic and now pw-volume) using `cargo install`. However pw-volume is not on `crates.io`

Could you publish it there? It should be quite easy [guide/docs](https://doc.rust-lang.org/cargo/reference/publishing.html)

- The following fields need to be added to `Cargo.toml`:
```
readme = "README.md"
description = "Basic interface to PipeWire volume controls"
repository = "https://github.com/smasher164/pw-volume"
license = "MIT"
keywords = ["pipewire", "volume"]
```
- and optionally this one:
```
categories = ["command-line-utilities"]
```
- then the version in Cargo.toml should probably be updated to reflect the github release

**Comment by dvdsk** [comment]
I just realize I can also use  `cargo install --git https://github.com/smasher164/pw-volume`. However I still think it would still be nice to have this on `crates.io`.

**Comment by smasher164** [comment]
Published the crate here: https://crates.io/crates/pw-volume

Thanks for filing this issue!
