### ISSUE TITLE
thread 'main' panic

### ISSUE THREAD

**Issue by AriaMoradi** [smasher164/pw-volume#16]
Hey, I installed 0.3.0 and it doesn't work
```
$ pw-volume status                 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to find device: 55', src/main.rs:397:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  pw-volume status
```

Running all other commands results in the same error.
I'm running latest version of everything on arch:
```
$ pacman -Q | grep pipe
gst-plugin-pipewire 1:0.3.52-1
libpipeline 1.5.6-1
pipewire 1:0.3.52-1
pipewire-alsa 1:0.3.52-1
pipewire-pulse 1:0.3.52-1
```

PS. I installed 0.2.0 and it works, the issue is somewhere between the two releases

**Comment by smasher164** [comment]
Do you mind uploading the output of `pw-dump` in a text file here? It will make it easy to add a test case for it, and figure out why it's failing.

**Comment by AriaMoradi** [comment]
[pw-dump-dump.txt](https://github.com/smasher164/pw-volume/files/8926130/pw-dump-dump.txt)

**Comment by smasher164** [comment]
If you are able to run with cargo, please try the latest `main`, and let know if that fixes your issue.
Thanks!

**Comment by AriaMoradi** [comment]
I packaged the git version for the aur and it worked (it's commit 45).

mentioning that these packages for Arch Linux exist in README might be helpful to users.

https://aur.archlinux.org/packages/pw-volume
https://aur.archlinux.org/packages/pw-volume-git

You could have something like: https://github.com/ThePBone/GalaxyBuds-BatteryLevel#aur

the commands are `yay -S pw-volume` and `yay -S pw-volume-git`
