### ISSUE TITLE
serde_json = "1.0.70" -> 1.0.79 required here

### ISSUE THREAD

**Issue by CaptainBloodz** [smasher164/pw-volume#27]
amd64 ~ # cat /etc/portage/patches/app-misc/pw-volume/pw-volume.patch
--- ./Cargo.toml   2023-02-04 15:36:22.572931530 +0300
+++ ./Cargo.toml   2023-02-04 15:37:02.106263422 +0300
@@ -13,7 +13,7 @@
 
 [dependencies]
 serde = { version = "1.0.130", features = ["derive"] }
-serde_json = "1.0.70"
+serde_json = "1.0.79"
 clap = "2.33.3"
 anyhow = "1.0.56"

Maybe I'm missing something?

[https://forums.gentoo.org/viewtopic-t-1161334-highlight-.html](url)

**Comment by smasher164** [comment]
Addressed in https://github.com/smasher164/pw-volume/commit/7db08494813ff1361d108e8a2988013684b47ab4
