### ISSUE TITLE
Provide precompiled

### ISSUE THREAD

**Issue by mizzunet** [smasher164/pw-volume#4]
Would you be able to release complied binary?

**Comment by smasher164** [comment]
Yes. Here is the link to the release.
https://github.com/smasher164/pw-volume/releases/tag/v0.1.0

Thanks for opening this issue!

---

Sidenote: I spent yesterday trying to get Rust under NixOS to cross-compile a static binary with MUSL, before I gave up and used docker. I'm now using https://github.com/messense/rust-musl-cross, which has pre-built docker images with musl for each target.
I added this commit https://github.com/smasher164/sway-tools/commit/3d6a8554b87bb90718b6a4d865dc4dc8fc24d6be to the sway-tools repo that lets me build a static binary for x64 and aarch64.

**Comment by mizzunet** [comment]
Awesome
